### ISSUE TITLE
Accessibility issue with rating

### ISSUE THREAD

**Issue by paulGeoghegan** [shoelace-style/webawesome-alpha#23] opened 2024-06-23 20:46 UTC
### Describe the bug
A bug is _a demonstrable problem_ caused by code in the library. Please provide a clear and concise description of what the bug is here.
Ratings are read correctly but the maxvalue of them is not. This is especially important for read only components since you can't manually check the maxvalue.

### To Reproduce

1. Go to https://backers.webawesome.com/docs/components/rating
2. Navigate to one of the rating components while using a screen reader
3. The current rating is read but the maxvalue is not

      ### Browser / OS
       - OS: Windows
       - Browser: Firefox
       - Browser version: 127.0.1
       - Screen Reader: NVDA

**Comment by KonnorRogers** [comment] 2024-06-25 19:56
@paulGeoghegan I believe this is kind of a duplicate of #24 whereby `role="slider"` doesn't read min / max values. (rating uses `role="slider"` "under the hood"

**Comment by paulGeoghegan** [comment] 2024-06-26 11:47
@KonnorRogers yes it is a duplicate then. Is there a way for me to view the source code yet?

**Comment by claviska** [comment] 2024-06-26 13:36
Not yet...we haven't planned a release date for WA Free's source.

**Closed by claviska** 2024-06-26 13:36 UTC
Labels: bug, duplicate, screenreader, NVDA
