### ISSUE TITLE
wa-progress-ring always displays full on Safari (both Mac and iOS)

### ISSUE THREAD

**Issue by julianrubisch** [shoelace-style/webawesome-alpha#89] opened 2024-10-24 15:33 UTC
### Describe the bug

On Safari, the progress ring SVG always displays as full even though`stroke-dashoffset` has the correct value.

### To Reproduce
Create a `<wa-progress-ring>` with a `value` lower than 100.

You can in fact even observe this on the doc site: https://backers.webawesome.com/docs/components/progress-ring

Looking at this it seems like the only example that's working correctly is the one with the `--size` CSS variable set?

### Screenshots
![Progress ring displaying wrong value in Safari](https://github.com/user-attachments/assets/ca100a1f-67a9-4628-97dc-ba2c8bdd99e0)

### Browser / OS
 - OS: Mac, iOS
 - Browser: Safari
 - Browser version: 17.6

**Comment by julianrubisch** [comment] 2024-10-24 15:33
cc @KonnorRogers

**Comment by KonnorRogers** [comment] 2024-10-24 16:09
This _feels_ like a Safari bug.


```css
    --size: 8rem;
    --track-width: 0.25rem;
```

Changing either of these to `em` or `px`, and only just one of them, fixes the issue. Something about calculating `rem * rem` is breaking Safari's calculations.

```css
    --size: 8rem;
    --track-width: 0.25em;
 
    --indicator-width: var(--track-width);

    --radius: calc(var(--size) / 2 - max(var(--track-width), var(--indicator-width)) * 0.5);
    --circumference: calc(var(--radius) * 2 * 3.141592654);

```

Seems like it may be worth putting a minimal reproduction together and submitting to Webkit bugs.

**Comment by LeaVerou** [comment] 2024-10-24 17:44
> This _feels_ like a Safari bug.
> 
> ```css
>     --size: 8rem;
>     --track-width: 0.25rem;
> ```
> 
> Changing either of these to `em` or `px`, and only just one of them, fixes the issue. Something about calculating `rem * rem` is breaking Safari's calculations.
> 
> ```css
>     --size: 8rem;
>     --track-width: 0.25em;
>  
>     --indicator-width: var(--track-width);
> 
>     --radius: calc(var(--size) / 2 - max(var(--track-width), var(--indicator-width)) * 0.5);
>     --circumference: calc(var(--radius) * 2 * 3.141592654);
> ```

`rem * rem` would be illegal (since you can't yet divide by lengths, and there's no `rem²` unit, but I don't see a `rem * rem` calculation here? `/` and `*` have higher precedence than `+` and `-` so the denominator of `var(--size)` is just the number `2`.

> Seems like it may be worth putting a minimal reproduction together and submitting to Webkit bugs.

👍🏼 Ping me when/if you do so I can get some WebKit folks to look at it.

---

That said, perhaps using `em` here is the right call regardless of this bug, do we want it to adapt its size from its context or be the same size regardless of where it's placed? If the former, then `em` would work better.

**Comment by claviska** [comment] 2024-10-28 15:59
Thanks for reporting this. A fix has landed and will be available in the next alpha release of Web Awesome.

**Closed** 2024-10-28 15:58 UTC
Labels: bug
