### ISSUE TITLE
Select element default default value doesn't work if you reload the page

### ISSUE THREAD

**Issue by dcarboMC** [shoelace-style/webawesome-alpha#99] opened 2024-11-27 06:32 UTC
### Describe the bug
When we provide to an wa-select element a default value separated by spaces (as the documentation says), the first time is working correctly, showing the selected values, but once you reload the page it doesn't show the values anymore. I did some tests and it seems a problem with the cache. 

### To Reproduce
https://jsfiddle.net/my38t7Lq/

First time:
![image](https://github.com/user-attachments/assets/e827302a-769f-4d67-b309-9274d83747f9)

Second and rest of times: 
![image](https://github.com/user-attachments/assets/ac10ef54-68b9-46f8-938f-db6320b0c57e)

### Browser / OS
 - OS: [Windows]
 - Browser: [Chrome]

**Comment by KonnorRogers** [comment] 2024-11-27 06:58
This _should_ be fixed in the next release.

Duplicate of #82

**Closed by KonnorRogers** 2024-11-27 06:58 UTC
Labels: bug
